# Experiment 10 : Create Dataset and Load Dataset
### Name : Ayush Pathare
### PRN: 25070123166
### Class: EnTC A-2

In [50]:
# Dataset Creation
import pandas as pd
data = {
    "Roll_No" : [101,102,103,104,105],
    "Gender" : ["Female","Male","Female","Male","Female"],
    "Department" : ["Computer","IT","ENTC","Mechanical","Computer"],
    "CGPA":[8.2,7.5,9.1,6.8,8.7],
    "Year" : [2020,2024,2026,2021,2022]
}
df = pd.DataFrame(data)
df.to_csv("students.csv",index=False)
print(df)
print("\n\n")
print(type(df),type(data))

   Roll_No  Gender  Department  CGPA  Year
0      101  Female    Computer   8.2  2020
1      102    Male          IT   7.5  2024
2      103  Female        ENTC   9.1  2026
3      104    Male  Mechanical   6.8  2021
4      105  Female    Computer   8.7  2022



<class 'pandas.core.frame.DataFrame'> <class 'dict'>

In [17]:
# Shape of Dataset
df.shape

(5, 5)

In [18]:
# Size of Dataset - All elements present in csv file
df.size

25

In [19]:
#Information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
 4   Year        5 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

In [24]:
df.describe()

          Roll_No     CGPA         Year
count    5.000000  5.00000     5.000000
mean   103.000000  8.06000  2022.600000
std      1.581139  0.92358     2.408319
min    101.000000  6.80000  2020.000000
25%    102.000000  7.50000  2021.000000
50%    103.000000  8.20000  2022.000000
75%    104.000000  8.70000  2024.000000
max    105.000000  9.10000  2026.000000

In [25]:
# Problem 1: Access info of column department
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Roll_No     5 non-null      int64
 1   Gender      5 non-null      object
 2   Department  5 non-null      object
 3   CGPA        5 non-null      float64
 4   Year        5 non-null      int64
dtypes: float64(1), int64(2), object(2)
memory usage: 332.0+ bytes

In [29]:
# Problem 2: Access information of PRN 103
df.loc[2]

Roll_No          103
Gender        Female
Department      ENTC
CGPA             9.1
Year            2026
Name: 2, dtype: object

In [34]:
# Problem 3: Find out data type of each column
df.dtypes

Roll_No         int64
Gender         object
Department     object
CGPA          float64
Year            int64
dtype: object

In [44]:
# Problem 4: Perform Mean, Median, Mode operations
mean = df["CGPA"].mean()
median = df["CGPA"].median()
mode = df["CGPA"].mode()

print("Mean: ",mean)
print("Median: ",median)
print("Mode: ",mode)

Mean:  8.059999999999999
Median:  8.2
Mode:  0    6.8
1    7.5
2    8.2
3    8.7
4    9.1
Name: CGPA, dtype: float64

In [46]:
# Problem 5: Insert a new column grade
df['Grade'] = ['First Class','Distinction','Second Class','First Class','Distinction']
print(df)

   Roll_No  Gender  Department  CGPA  Year         Grade
0      101  Female    Computer   8.2  2020   First Class
1      102    Male          IT   7.5  2024   Distinction
2      103  Female        ENTC   9.1  2026  Second Class
3      104    Male  Mechanical   6.8  2021   First Class
4      105  Female    Computer   8.7  2022   Distinction

In [52]:
# Problem 6: Delete Gender Column
print(df, end="\n\n")
print("After Deleting a column -")
df.drop("Gender",axis=1, inplace=True)
print(df)

   Roll_No  Gender  Department  CGPA  Year
0      101  Female    Computer   8.2  2020
1      102    Male          IT   7.5  2024
2      103  Female        ENTC   9.1  2026
3      104    Male  Mechanical   6.8  2021
4      105  Female    Computer   8.7  2022

After Deleting a column -
   Roll_No  Department  CGPA  Year
0      101    Computer   8.2  2020
1      102          IT   7.5  2024
2      103        ENTC   9.1  2026
3      104  Mechanical   6.8  2021
4      105    Computer   8.7  2022

In [54]:
# Problem 7: CGPA of Topper
top = df["CGPA"].max()
print("CGPA of Topper: ",top)

CGPA of Topper:  9.1

In [57]:
# Problem 8: CGPA OF PRN 105
cg5 = df.loc[4,"CGPA"]
print("CGPA of PRN 105: ",cg5)

CGPA of PRN 105:  8.7

In [58]:
# Upload the dataset and read it
import pandas as pd
import numpy as np
df = pd.read_csv('Cars93.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [62]:
print("Dataset Size: ",df.size,end="\n")
print("Dataset Shape: ",df.shape)

Dataset Size:  930
Dataset Shape:  (93, 10)

In [63]:
print(df.head(),end="\n")
print(df.tail())

  Manufacturer    Model     Type  Price  MPG.city             AirBags  \
0        Acura  Integra    Small   15.9        25                 NaN
1        Acura   Legend  Midsize   33.9        18  Driver & Passenger
2         Audi       90  Compact   29.1        20         Driver only
3         Audi      100  Midsize   37.7        19  Driver & Passenger
4          BMW     535i  Midsize   30.0        22         Driver only

   Horsepower  Passengers  Rear.seat.room  Luggage.room
0         140           5            26.5          11.0
1         200           5            30.0          15.0
2         172           5            28.0          14.0
3         172           6            31.0          17.0
4         208           4            27.0          13.0
   Manufacturer    Model     Type  Price  MPG.city             AirBags  \
88   Volkswagen  Eurovan      Van   19.7        17                 NaN
89   Volkswagen   Passat  Compact   20.0        21                 NaN
90   Volkswagen  Corrado   Sporty   23.3        18                 NaN
91        Volvo      240  Compact   22.7        21         Driver only
92        Volvo      850  Midsize   26.7        20  Driver & Passenger

    Horsepower  Passengers  Rear.seat.room  Luggage.room
88         109           7            34.0           NaN
89         134           5            31.5          14.0
90         178           4            26.0          15.0
91         114           5            29.5          14.0
92         168           5            30.0          15.0

In [64]:
# Mini-Project DataSet
import pandas as pd
import numpy as np
df = pd.read_csv('/content/netflix_titles.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB