# Experiment 13 - Data Binning and Formatting

Name - Ayush Pathare  
PRN - 25070123166  
Class - E&TC A2

In [ ]:
import pandas as pd
import numpy as np

data = {
    'Product' : ['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price' : [55000,20000,30000,2000,8000,45000],
    'Units_Sold':[25,60,35,80,50,15]
}

df = pd.DataFrame(data)
df

      Product  Price  Units_Sold
0      Laptop  55000          25
1      Mobile  20000          60
2      Tablet  30000          35
3  Headphones   2000          80
4  Smartwatch   8000          50
5      Camera  45000          15

In [ ]:
# Data Binning

bins = [0,10000,30000,60000]
labels = ['Low','Medium','High']
df['Price_Category'] = pd.cut(df['Price'],bins=bins,labels=labels)

bins = [0,25,50,75,100]
labels = ['Low Sales','Medium Sales','High Sales','Very High Sales']
df['Sales_Category'] = pd.cut(df['Units_Sold'],bins=bins,labels=labels)
df

      Product  Price  Units_Sold Price_Category   Sales_Category
0      Laptop  55000          25           High        Low Sales
1      Mobile  20000          60         Medium       High Sales
2      Tablet  30000          35         Medium     Medium Sales
3  Headphones   2000          80            Low  Very High Sales
4  Smartwatch   8000          50            Low     Medium Sales
5      Camera  45000          15           High        Low Sales

In [ ]:
#Data Formatting
#Convert Data Type

print(df.dtypes,end='\n\n--------------------------\n\n')
df['Units_Sold'] = df['Units_Sold'].astype(float)
print(df.dtypes)

Product             object
Price                int64
Units_Sold           int64
Price_Category    category
Sales_Category    category
dtype: object

--------------------------

Product             object
Price                int64
Units_Sold         float64
Price_Category    category
Sales_Category    category
dtype: object

In [ ]:
#Convert Text to Uppercase
df['Product'] = df['Product'].str.upper()
df

      Product  Price  Units_Sold Price_Category   Sales_Category
0      LAPTOP  55000        25.0           High        Low Sales
1      MOBILE  20000        60.0         Medium       High Sales
2      TABLET  30000        35.0         Medium     Medium Sales
3  HEADPHONES   2000        80.0            Low  Very High Sales
4  SMARTWATCH   8000        50.0            Low     Medium Sales
5      CAMERA  45000        15.0           High        Low Sales

In [ ]:
# Rounding Values
df['Price'] = df['Price'].round(2)
df

      Product  Price  Units_Sold Price_Category   Sales_Category
0      LAPTOP  55000        25.0           High        Low Sales
1      MOBILE  20000        60.0         Medium       High Sales
2      TABLET  30000        35.0         Medium     Medium Sales
3  HEADPHONES   2000        80.0            Low  Very High Sales
4  SMARTWATCH   8000        50.0            Low     Medium Sales
5      CAMERA  45000        15.0           High        Low Sales

In [ ]:
#Additional Operations
#Sort Data
sorted_df = df.sort_values(by='Price')
print(sorted_df)

      Product  Price  Units_Sold Price_Category   Sales_Category
3  HEADPHONES   2000        80.0            Low  Very High Sales
4  SMARTWATCH   8000        50.0            Low     Medium Sales
1      MOBILE  20000        60.0         Medium       High Sales
2      TABLET  30000        35.0         Medium     Medium Sales
5      CAMERA  45000        15.0           High        Low Sales
0      LAPTOP  55000        25.0           High        Low Sales

In [ ]:
#Display Unique Values
print(df['Price_Category'].unique())

['High', 'Medium', 'Low']
Categories (3, object): ['Low' < 'Medium' < 'High']

In [ ]:
#Dataset: Food Delivery Orders

import pandas as pd
import numpy as np

data = {
    'Order_ID':['01','02','03','04','05','06','07','08'],
    'Order_Value':[250,450,120,600,300,150,500,220],
    'Delivery_Time':[30,45,25,60,35,20,50,28],
    'Distance_km':[5,8,3,10,6,2,9,4]
}
df = pd.DataFrame(data)
df

  Order_ID  Order_Value  Delivery_Time  Distance_km
0       01          250             30            5
1       02          450             45            8
2       03          120             25            3
3       04          600             60           10
4       05          300             35            6
5       06          150             20            2
6       07          500             50            9
7       08          220             28            4

In [ ]:
#Binning Order Value
bins = [0,200,400,700]
labels = ['Low Order','Medium Order','High Order']
df['Order_Category'] = pd.cut(df['Order_Value'],bins=bins,labels=labels)
df

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category
0       01          250             30            5   Medium Order
1       02          450             45            8     High Order
2       03          120             25            3      Low Order
3       04          600             60           10     High Order
4       05          300             35            6   Medium Order
5       06          150             20            2      Low Order
6       07          500             50            9     High Order
7       08          220             28            4   Medium Order

In [ ]:
#Binning Delivery Time
bins2 = [0,30,45,70]
labels2 = ['Fast','Normal','Slow']
df['Delivery_Category'] = pd.cut(df['Delivery_Time'],bins=bins2,labels=labels2)
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery_Category
0,01,250,30,5,Medium Order,Fast
1,02,450,45,8,High Order,Normal
2,03,120,25,3,Low Order,Fast
3,04,600,60,10,High Order,Slow
4,05,300,35,6,Medium Order,Normal
5,06,150,20,2,Low Order,Fast
6,07,500,50,9,High Order,Slow
7,08,220,28,4,Medium Order,Fast

In [ ]:
#Data Formatting Example
#Convert Distance to Float
df['Distance_km']= df['Distance_km'].astype(float)
df
#

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery_Category
0,01,250,30,5.0,Medium Order,Fast
1,02,450,45,8.0,High Order,Normal
2,03,120,25,3.0,Low Order,Fast
3,04,600,60,10.0,High Order,Slow
4,05,300,35,6.0,Medium Order,Normal
5,06,150,20,2.0,Low Order,Fast
6,07,500,50,9.0,High Order,Slow
7,08,220,28,4.0,Medium Order,Fast

In [ ]:
#Convert Order_ID to Uppercase
df['Order_Category'] = df['Order_Category'].str.upper()
df

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery_Category
0,01,250,30,5.0,MEDIUM ORDER,Fast
1,02,450,45,8.0,HIGH ORDER,Normal
2,03,120,25,3.0,LOW ORDER,Fast
3,04,600,60,10.0,HIGH ORDER,Slow
4,05,300,35,6.0,MEDIUM ORDER,Normal
5,06,150,20,2.0,LOW ORDER,Fast
6,07,500,50,9.0,HIGH ORDER,Slow
7,08,220,28,4.0,MEDIUM ORDER,Fast

In [ ]:
#Check Data Types
print(df.dtypes)

Order_ID               object
Order_Value             int64
Delivery_Time           int64
Distance_km           float64
Order_Category         object
Delivery_Category    category
dtype: object

In [ ]:
#Unique Categories
print(df['Order_Category'].unique())

['MEDIUM ORDER' 'HIGH ORDER' 'LOW ORDER']

In [ ]:
#Count Categories
print(df['Order_Category'].value_counts())

Order_Category
MEDIUM ORDER    3
HIGH ORDER      3
LOW ORDER       2
Name: count, dtype: int64

In [ ]:
#Sorting
print(df.sort_values(by='Order_Value'))
df

  Order_ID  Order_Value  Delivery_Time  Distance_km Order_Category  \
2       03          120             25          3.0      LOW ORDER
5       06          150             20          2.0      LOW ORDER
7       08          220             28          4.0   MEDIUM ORDER
0       01          250             30          5.0   MEDIUM ORDER
4       05          300             35          6.0   MEDIUM ORDER
1       02          450             45          8.0     HIGH ORDER
6       07          500             50          9.0     HIGH ORDER
3       04          600             60         10.0     HIGH ORDER

  Delivery_Category
2              Fast
5              Fast
7              Fast
0              Fast
4            Normal
1            Normal
6              Slow
3              Slow

,Order_ID,Order_Value,Delivery_Time,Distance_km,Order_Category,Delivery_Category
0,01,250,30,5.0,MEDIUM ORDER,Fast
1,02,450,45,8.0,HIGH ORDER,Normal
2,03,120,25,3.0,LOW ORDER,Fast
3,04,600,60,10.0,HIGH ORDER,Slow
4,05,300,35,6.0,MEDIUM ORDER,Normal
5,06,150,20,2.0,LOW ORDER,Fast
6,07,500,50,9.0,HIGH ORDER,Slow
7,08,220,28,4.0,MEDIUM ORDER,Fast