# Exp 9 - Tools in EDA
## Pandas Library

Name - Ayush Pathare  
PRN : 25070123166  
Batch : E&TC A2

In [1]:
import pandas as pd

s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [6]:
# Create DataFrame
data = {
    "Name" : ["A","B","C"],
    "Marks" : [85,90,78]
}
df = pd.DataFrame(data)
df

  Name  Marks
0    A     85
1    B     90
2    C     78

In [9]:
print(df.head(), end="\n\n")
print(df.tail())

  Name  Marks
0    A     85
1    B     90
2    C     78

  Name  Marks
0    A     85
1    B     90
2    C     78

In [10]:
# Find the Structure of the DataFrame
df.shape

(3, 2)

In [11]:
# Find the Dimension of DataFrame
df.ndim

2

In [13]:
#Find the size of df
df.size

6

In [14]:
#Display Column Names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [16]:
#Check data types of each column
df.dtypes

Name     object
Marks     int64
dtype: object

In [17]:
#Access Individual Column
df['Name']

0    A
1    B
2    C
Name: Name, dtype: object

In [24]:
#Access Specific Row
df.loc[2]

Name      C
Marks    78
Name: 2, dtype: object

In [44]:
#Add a new column
df['Grade'] = ['First Class','Distinction','Second Class']
df

  Name  Marks         Grade
0    A     88   First Class
1    B     97   Distinction
2    C     78  Second Class

In [45]:
#Update Data in DataFrame
#Change Marks of student A to 88
df.loc[1,"Marks"] = 97
df

  Name  Marks         Grade
0    A     88   First Class
1    B     97   Distinction
2    C     78  Second Class

In [46]:
#Delete a comlumn
df.drop("Grade",axis=1, inplace=True)
df

  Name  Marks
0    A     88
1    B     97
2    C     78

In [55]:
#Perform Basic Statistical Analysis
mean1 = df["Marks"].mean()
print(f"{mean1:.2f}")

87.67

In [61]:
#Max and Min Values
min1 = df["Marks"].min()
max1 = df["Marks"].max()

print(min1,max1)

78 97

In [62]:
#Apply Condition (Filtering)
#Display Students scoring more than 80

df[df['Marks'] > 80]

  Name  Marks
0    A     88
1    B     97