# Experiment 12 : Data Wrangling
### Preprocessing Dataset and dealing with Missing Values
---
Name - Ayush Pathare  
PRN - 25070123166  
Batch - E&TC A2

---

In [3]:
import pandas as pd
import numpy as np

df1 = pd.DataFrame({'C1':[11,21,np.nan],
                    'C2':[15,np.nan,np.nan],
                    'C3':[10,20,30]})
df1

     C1    C2  C3
0  11.0  15.0  10
1  21.0   NaN  20
2   NaN   NaN  30

In [4]:
df1.isna() #Boolean function

      C1     C2     C3
0  False  False  False
1  False   True  False
2   True   True  False

In [6]:
df1.isna().sum() #Columnwise NA values

C1    1
C2    2
C3    0
dtype: int64

In [11]:
df1.dropna() #NaN Rows are dropped

     C1    C2  C3
0  11.0  15.0  10

In [13]:
df1.fillna('default') # # Fill missing values with something

        C1       C2  C3
0     11.0     15.0  10
1     21.0  default  20
2  default  default  30

In [14]:
df1.fillna(df1.mean()) # Mean values of columns are calculated

     C1    C2  C3
0  11.0  15.0  10
1  21.0  15.0  20
2  16.0  15.0  30

In [16]:
#Dataset-1

import pandas as pd

data = {
    "Roll No": [101, 102, 103, 104, 105],
    "Name": ["Asha", "Rohan", "Meera", "Karan", "Anil"],
    "Age": [20, "-", 21, 20, "22"],
    "Marks": [85, 90, "-", 88, 76],
    "Department": ["CSE", "IT", "CSE", "cse", "E&TC"],
    "Admission_Date": ["01-06-2023","03-06-2023","05-06-2023","07-06-2023","10/06/23"]
}

df = pd.DataFrame(data)

# Save as CSV
df.to_csv("student_data.csv", index=False)

df

   Roll No   Name Age Marks Department Admission_Date
0      101   Asha  20    85        CSE     01-06-2023
1      102  Rohan   -    90         IT     03-06-2023
2      103  Meera  21     -        CSE     05-06-2023
3      104  Karan  20    88        cse     07-06-2023
4      105   Anil  22    76       E&TC       10/06/23

In [20]:
# Step 2: Replace '-' with NaN to mark missing values

df.replace("-", np.nan, inplace=True)

# Convert columns to numeric where needed
df["Age"] = pd.to_numeric(df["Age"], errors="coerce")
df["Marks"] = pd.to_numeric(df["Marks"], errors="coerce")

'''
When converting data (strings --> datetime), if some values are invalid or
cannot be converted, instead of throwing an error, it will: replace invalid values
with NaT (Not a Time).
'''
df

   Roll No   Name   Age  Marks Department Admission_Date
0      101   Asha  20.0   85.0        CSE     01-06-2023
1      102  Rohan   NaN   90.0         IT     03-06-2023
2      103  Meera  21.0    NaN        CSE     05-06-2023
3      104  Karan  20.0   88.0        cse     07-06-2023
4      105   Anil  22.0   76.0       E&TC       10/06/23

In [21]:
# Step 3: Check Missing Values
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Roll No           0
Name              0
Age               1
Marks             1
Department        0
Admission_Date    0
dtype: int64

In [25]:
import warnings
warnings.filterwarnings("ignore")


# Fill missing age with mean age
df["Age"].fillna(df["Age"].mean(), inplace=True)

#Fill missing marks with median
df["Marks"].fillna(df["Marks"].median(), inplace=True)

df

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00   86.5        CSE     05-06-2023
3      104  Karan  20.00   88.0        cse     07-06-2023
4      105   Anil  22.00   76.0       E&TC       10/06/23

In [26]:
print(df.isnull().sum())

Roll No           0
Name              0
Age               0
Marks             0
Department        0
Admission_Date    0
dtype: int64

In [29]:
# Step 5: Fix inconsistent text formatting

df["Department"] = df["Department"].str.upper()
df

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     01-06-2023
1      102  Rohan  20.75   90.0         IT     03-06-2023
2      103  Meera  21.00   86.5        CSE     05-06-2023
3      104  Karan  20.00   88.0        CSE     07-06-2023
4      105   Anil  22.00   76.0       E&TC       10/06/23

In [33]:
# Step 6: Convert Admission_Date to standard datetime format

df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], errors='coerce')
df

# If a value cannot be converted to valid date, pandas will replace it with NaT

   Roll No   Name    Age  Marks Department Admission_Date
0      101   Asha  20.00   85.0        CSE     2023-01-06
1      102  Rohan  20.75   90.0         IT     2023-03-06
2      103  Meera  21.00   86.5        CSE     2023-05-06
3      104  Karan  20.00   88.0        CSE     2023-07-06
4      105   Anil  22.00   76.0       E&TC            NaT

In [34]:
# Step 7: Save cleaned dataset

df.to_csv("cleaned_studentdata.csv",index=False)
print("Cleaned CSV file saved as cleaned_studentdata.csv")

Cleaned CSV file saved as cleaned_studentdata.csv

Wokring on Cars93 Dataset

In [36]:
# Working with missing values DataSET 2

import pandas as pd
import numpy as np

df=pd.read_csv("Cars93.csv")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93 entries, 0 to 92
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Manufacturer    93 non-null     object
 1   Model           93 non-null     object
 2   Type            93 non-null     object
 3   Price           93 non-null     float64
 4   MPG.city        93 non-null     int64
 5   AirBags         59 non-null     object
 6   Horsepower      93 non-null     int64
 7   Passengers      93 non-null     int64
 8   Rear.seat.room  91 non-null     float64
 9   Luggage.room    82 non-null     float64
dtypes: float64(3), int64(3), object(4)
memory usage: 7.4+ KB

In [37]:
df.isna().sum() #Attributes are displayed

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room      11
dtype: int64

Imputing the Missing Value

In [40]:
# Imputing the Missing Value
# 1. Luggage Room

df['Luggage.room'] = df['Luggage.room'].fillna(value=df['Luggage.room'].mean())
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     2
Luggage.room       0
dtype: int64

In [42]:
# 2. Rear Seat Room
df['Rear.seat.room'] = df['Rear.seat.room'].fillna(value=df['Rear.seat.room'].mean())
df.isna().sum()

Manufacturer       0
Model              0
Type               0
Price              0
MPG.city           0
AirBags           34
Horsepower         0
Passengers         0
Rear.seat.room     0
Luggage.room       0
dtype: int64

In [43]:
# 3. Air Bags
df['AirBags'] = df['AirBags'].fillna(value=df['AirBags'].mode().values[0])
df.isna().sum()

Manufacturer      0
Model             0
Type              0
Price             0
MPG.city          0
AirBags           0
Horsepower        0
Passengers        0
Rear.seat.room    0
Luggage.room      0
dtype: int64

In [44]:
# Save cleaned data
df.to_csv("cleaned_cars93.csv",index=False)
print("Cleaned CSV file saved as cleaned_cars93.csv")

Cleaned CSV file saved as cleaned_cars93.csv