# Experiment 14
## Part - A : Data Normalization
---
Name - Ayush Pathare  
PRN : 25070123166  
Batch : E&TC A2

---

In [ ]:
#Dataset

import pandas as pd
import numpy as np

data = {
    'Product' : ['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'],
    'Price' : [55000,20000,30000,2000,8000,45000],
    'Units_Sold':[25,60,35,80,50,15],
    'Discount' : [10,15,12,20,18,8]
}

df = pd.DataFrame(data)

print("Original Dataset")
print(df)

Original Dataset
      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [ ]:
#1. Min-Max Normalization
# for Price

df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())

print("\nMin-Max Normalized Price:")
print(df[['Product','Price', 'Price_MinMax']])

Min-Max Normalized Price:
      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [ ]:
#1. Min-Max Normalization
# for Discount

df['Discount_MinMax'] = (df['Discount'] - df['Discount'].min()) / (df['Discount'].max() - df['Discount'].min())
print("\nMin-Max Normalized Discount:")
print(df[['Product','Discount', 'Discount_MinMax']])

Min-Max Normalized Discount:
      Product  Discount  Discount_MinMax
0      Laptop        10         0.166667
1      Mobile        15         0.583333
2      Tablet        12         0.333333
3  Headphones        20         1.000000
4  Smartwatch        18         0.833333
5      Camera         8         0.000000

In [ ]:
#2. Z-Score Normalization
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()

print("\nZ-Score Normalized Units Sold:")
print(df[['Product','Units_Sold', 'Units_Zscore']])

Z-Score Normalized Units Sold:
      Product  Units_Sold  Units_Zscore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

In [ ]:
#3. Decimal Scaling - For Price
df['Price_Decimal'] = df['Price'] / 100000

print("\nDecimal Scaled Price:")
print(df[['Product','Price', 'Price_Decimal']])

Decimal Scaled Price:
      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

In [ ]:
#3. Decimal Scaling - For Discount
df['Discount_Decimal'] = df['Discount'] / 100

print("\nDecimal Scaled Discount:")
print(df[['Product','Discount', 'Discount_Decimal']])

Decimal Scaled Discount:
      Product  Discount  Discount_Decimal
0      Laptop        10              0.10
1      Mobile        15              0.15
2      Tablet        12              0.12
3  Headphones        20              0.20
4  Smartwatch        18              0.18
5      Camera         8              0.08

In [ ]:
# Normalize Multiple Columns

cols = ['Price', 'Units_Sold', 'Discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())

print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

---
# Experiment 14
## Part B - Type Conversion
---

In [ ]:
data = {
        'Order_ID':['101','102','103','104','105','106'],
        'Customer_Gender' : ['Male','Female','Female','Male','Female','Male'],
        'Payment_Method' : ['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
        'Product_Category' : ['Electronics','Clothing','Home','Electronics','Beauty','Elctronics'],
        'City' : ['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
        'Order_Value' : [4500,2300,3200,5200,1800,4100]
}
df = pd.DataFrame(data)
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value
0,101,Male,UPI,Electronics,Pune,4500
1,102,Female,Credit Card,Clothing,Mumbai,2300
2,103,Female,Debit Card,Home,Delhi,3200
3,104,Male,COD,Electronics,Bangalore,5200
4,105,Female,UPI,Beauty,Pune,1800
5,106,Male,Debit Card,Elctronics,Hyderabad,4100

In [ ]:
# Method 1 : Label Encoding

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label
0,101,Male,UPI,Electronics,Pune,4500,1
1,102,Female,Credit Card,Clothing,Mumbai,2300,0
2,103,Female,Debit Card,Home,Delhi,3200,0
3,104,Male,COD,Electronics,Bangalore,5200,1
4,105,Female,UPI,Beauty,Pune,1800,0
5,106,Male,Debit Card,Elctronics,Hyderabad,4100,1

In [ ]:
# Method 2 : One-Hot Encoding

df_encoded = pd.get_dummies(df, columns=['Payment_Method'])

print(df_encoded)

  Order_ID Customer_Gender Product_Category       City  Order_Value  \
0      101            Male      Electronics       Pune         4500
1      102          Female         Clothing     Mumbai         2300
2      103          Female             Home      Delhi         3200
3      104            Male      Electronics  Bangalore         5200
4      105          Female           Beauty       Pune         1800
5      106            Male       Elctronics  Hyderabad         4100

   Gender_Label  Payment_Method_COD  Payment_Method_Credit Card  \
0             1               False                       False
1             0               False                        True
2             0               False                       False
3             1                True                       False
4             0               False                       False
5             1               False                       False

   Payment_Method_Debit Card  Payment_Method_UPI
0                      False                True
1                      False               False
2                       True               False
3                      False               False
4                      False                True
5                       True               False

In [ ]:
# Method 3 : Encoding Multiple Columns
df_multi = pd.get_dummies(df, columns = ['Product_Category','City'])
print(df_multi.head())

  Order_ID Customer_Gender Payment_Method  Order_Value  Gender_Label  \
0      101            Male            UPI         4500             1
1      102          Female    Credit Card         2300             0
2      103          Female     Debit Card         3200             0
3      104            Male            COD         5200             1
4      105          Female            UPI         1800             0

   Product_Category_Beauty  Product_Category_Clothing  \
0                    False                      False
1                    False                       True
2                    False                      False
3                    False                      False
4                     True                      False

   Product_Category_Elctronics  Product_Category_Electronics  \
0                        False                          True
1                        False                         False
2                        False                         False
3                        False                          True
4                        False                         False

   Product_Category_Home  City_Bangalore  City_Delhi  City_Hyderabad  \
0                  False           False       False           False
1                  False           False       False           False
2                   True           False        True           False
3                  False            True       False           False
4                  False           False       False           False

   City_Mumbai  City_Pune
0        False       True
1         True      False
2        False      False
3        False      False
4        False       True

In [ ]:
# Method 4 : Dummy Encoding (Drop First)
df_dummy = pd.get_dummies(df, columns = ['Payment_Method'], drop_first = True)
print(df_dummy)

  Order_ID Customer_Gender Product_Category       City  Order_Value  \
0      101            Male      Electronics       Pune         4500
1      102          Female         Clothing     Mumbai         2300
2      103          Female             Home      Delhi         3200
3      104            Male      Electronics  Bangalore         5200
4      105          Female           Beauty       Pune         1800
5      106            Male       Elctronics  Hyderabad         4100

   Gender_Label  Payment_Method_Credit Card  Payment_Method_Debit Card  \
0             1                       False                      False
1             0                        True                      False
2             0                       False                       True
3             1                       False                      False
4             0                       False                      False
5             1                       False                       True

   Payment_Method_UPI
0                True
1               False
2               False
3               False
4                True
5               False

Amazon DataSet Operations

In [1]:
import pandas as pd
df = pd.read_csv('/content/amazon_products_dataset_Expt-14.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    50 non-null     object
 1   Product_Name  50 non-null     object
 2   Price         50 non-null     int64
 3   Rating        50 non-null     float64
 4   Reviews       50 non-null     int64
 5   Units_Sold    50 non-null     int64
dtypes: float64(1), int64(3), object(2)
memory usage: 2.5+ KB

In [2]:
# Data Normalization - Multiple Columns [MinMax Method]

# Normalize Multiple Columns

cols = ['Price','Rating','Reviews', 'Units_Sold']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())

print("\nNormalized Dataset")
print(df_norm)

Normalized Dataset
       Price    Rating   Reviews  Units_Sold
0   0.020243  0.428571  0.291005    0.518519
1   0.048583  0.714286  0.148148    0.277778
2   0.016194  0.142857  0.119048    0.203704
3   0.089069  0.857143  0.444444    0.629630
4   0.149798  0.571429  0.695767    0.833333
5   0.036437  0.285714  0.351852    0.592593
6   0.024291  0.000000  0.052910    0.129630
7   0.064777  0.428571  0.185185    0.351852
8   0.210526  1.000000  0.378307    0.481481
9   0.028340  0.285714  0.089947    0.222222
10  0.311741  0.857143  1.000000    1.000000
11  0.174089  0.714286  0.444444    0.407407
12  0.052632  0.571429  0.232804    0.500000
13  0.016194  0.142857  0.031746    0.092593
14  0.024291  0.285714  0.119048    0.240741
15  0.251012  0.857143  0.497354    0.444444
16  0.036437  0.428571  0.089947    0.259259
17  0.068826  0.571429  0.312169    0.648148
18  0.109312  0.714286  0.814815    0.851852
19  0.040486  0.428571  0.148148    0.351852
20  0.008097  0.000000  0.000000    0.148148
21  0.089069  0.571429  0.272487    0.444444
22  0.352227  0.857143  0.219577    0.185185
23  0.020243  0.285714  0.079365    0.259259
24  0.129555  0.714286  0.444444    0.592593
25  0.174089  0.571429  0.148148    0.166667
26  0.514170  1.000000  0.708995    0.129630
27  0.076923  0.428571  0.232804    0.370370
28  0.016194  0.285714  0.121693    0.314815
29  0.048583  0.428571  0.150794    0.351852
30  0.392713  0.857143  0.444444    0.240741
31  0.230769  0.714286  0.351852    0.203704
32  0.129555  0.571429  0.550265    0.666667
33  0.473684  0.857143  0.272487    0.092593
34  0.635628  1.000000  0.444444    0.037037
35  0.012146  0.142857  0.007937    0.166667
36  0.020243  0.285714  0.126984    0.462963
37  0.000000  0.000000  0.047619    0.574074
38  0.028340  0.428571  0.079365    0.259259
39  0.048583  0.571429  0.026455    0.111111
40  0.109312  0.714286  0.113757    0.148148
41  0.433198  0.857143  0.206349    0.074074
42  0.190283  0.571429  0.444444    0.351852
43  1.000000  1.000000  0.365079    0.000000
44  0.068826  0.428571  0.259259    0.444444
45  0.311741  0.857143  0.470899    0.240741
46  0.757085  0.714286  0.325397    0.092593
47  0.089069  0.571429  0.148148    0.185185
48  0.129555  0.428571  0.119048    0.148148
49  0.028340  0.285714  0.089947    0.314815

In [3]:
# Data Normalization - Z-Score Normalization

cols_2 = ['Price','Rating','Reviews', 'Units_Sold']
df_norm2 = (df[cols_2] - df[cols_2].mean()) / df[cols_2].std()

print("\nZ-Score Normalized Units Sold:")
print(df_norm2)

Z-Score Normalized Units Sold:
       Price    Rating   Reviews  Units_Sold
0  -0.692019 -0.421580  0.075943    0.812282
1  -0.557310  0.606665 -0.577069   -0.260855
2  -0.711263 -1.449825 -0.710090   -0.591051
3  -0.364869  1.120787  0.777327    1.307576
4  -0.076207  0.092542  1.926145    2.215615
5  -0.615043 -0.935703  0.354078    1.142478
6  -0.672775 -1.963948 -1.012411   -0.921247
7  -0.480334 -0.421580 -0.407770    0.069341
8   0.212455  1.634910  0.475006    0.647184
9  -0.653531 -0.935703 -0.843111   -0.508502
10  0.693559  1.120787  3.316819    2.958556
11  0.039258  0.606665  0.777327    0.316988
12 -0.538066  0.092542 -0.190099    0.729733
13 -0.711263 -1.449825 -1.109154   -1.086345
14 -0.672775 -0.935703 -0.710090   -0.425953
15  0.404897  1.120787  1.019183    0.482086
16 -0.615043 -0.421580 -0.843111   -0.343404
17 -0.461090  0.092542  0.172685    1.390125
18 -0.268648  0.606665  2.470321    2.298164
19 -0.595799 -0.421580 -0.577069    0.069341
20 -0.749752 -1.963948 -1.254267   -0.838698
21 -0.364869  0.092542 -0.008707    0.482086
22  0.886000  1.120787 -0.250563   -0.673600
23 -0.692019 -0.935703 -0.891483   -0.343404
24 -0.172428  0.606665  0.777327    1.142478
25  0.039258  0.092542 -0.577069   -0.756149
26  1.655766  1.634910  1.986609   -0.921247
27 -0.422601 -0.421580 -0.190099    0.151890
28 -0.711263 -0.935703 -0.697998   -0.095757
29 -0.557310 -0.421580 -0.564977    0.069341
30  1.078442  1.120787  0.777327   -0.425953
31  0.308676  0.606665  0.354078   -0.591051
32 -0.172428  0.092542  1.261039    1.472674
33  1.463325  1.120787 -0.008707   -1.086345
34  2.233090  1.634910  0.777327   -1.333992
35 -0.730508 -1.449825 -1.217989   -0.756149
36 -0.692019 -0.935703 -0.673812    0.564635
37 -0.788240 -1.963948 -1.036597    1.059929
38 -0.653531 -0.421580 -0.891483   -0.343404
39 -0.557310  0.092542 -1.133339   -1.003796
40 -0.268648  0.606665 -0.734276   -0.838698
41  1.270883  1.120787 -0.311027   -1.168894
42  0.116235  0.092542  0.777327    0.069341
43  3.965063  1.634910  0.414542   -1.499090
44 -0.461090 -0.421580 -0.069171    0.482086
45  0.693559  1.120787  0.898255   -0.425953
46  2.810415  0.606665  0.233150   -1.086345
47 -0.364869  0.092542 -0.577069   -0.673600
48 -0.172428 -0.421580 -0.710090   -0.838698
49 -0.653531 -0.935703 -0.843111   -0.095757

In [8]:
# Data Normalization - Decimal Scaling

df_price = df['Price'] / 100000
df_rating = df['Rating'] / 10
df_reviews = df['Reviews'] / 10000
df_units = df['Units_Sold'] / 1000

df_norm = pd.concat([df_price,df_rating,df_reviews,df_units], axis = 1)
print("\nDecimal Scaled Values:")
print(df_norm)

Decimal Scaled Values:
      Price  Rating  Reviews  Units_Sold
0   0.00799    0.43    0.152        0.35
1   0.01499    0.45    0.098        0.22
2   0.00699    0.41    0.087        0.18
3   0.02499    0.46    0.210        0.41
4   0.03999    0.44    0.305        0.52
5   0.01199    0.42    0.175        0.39
6   0.00899    0.40    0.062        0.14
7   0.01899    0.43    0.112        0.26
8   0.05499    0.47    0.185        0.33
9   0.00999    0.42    0.076        0.19
10  0.07999    0.46    0.420        0.61
11  0.04599    0.45    0.210        0.29
12  0.01599    0.44    0.130        0.34
13  0.00699    0.41    0.054        0.12
14  0.00899    0.42    0.087        0.20
15  0.06499    0.46    0.230        0.31
16  0.01199    0.43    0.076        0.21
17  0.01999    0.44    0.160        0.42
18  0.02999    0.45    0.350        0.53
19  0.01299    0.43    0.098        0.26
20  0.00499    0.40    0.042        0.15
21  0.02499    0.44    0.145        0.31
22  0.08999    0.46    0.125        0.17
23  0.00799    0.42    0.072        0.21
24  0.03499    0.45    0.210        0.39
25  0.04599    0.44    0.098        0.16
26  0.12999    0.47    0.310        0.14
27  0.02199    0.43    0.130        0.27
28  0.00699    0.42    0.088        0.24
29  0.01499    0.43    0.099        0.26
30  0.09999    0.46    0.210        0.20
31  0.05999    0.45    0.175        0.18
32  0.03499    0.44    0.250        0.43
33  0.11999    0.46    0.145        0.12
34  0.15999    0.47    0.210        0.09
35  0.00599    0.41    0.045        0.16
36  0.00799    0.42    0.090        0.32
37  0.00299    0.40    0.060        0.38
38  0.00999    0.43    0.072        0.21
39  0.01499    0.44    0.052        0.13
40  0.02999    0.45    0.085        0.15
41  0.10999    0.46    0.120        0.11
42  0.04999    0.44    0.210        0.26
43  0.24999    0.47    0.180        0.07
44  0.01999    0.43    0.140        0.31
45  0.07999    0.46    0.220        0.20
46  0.18999    0.45    0.165        0.12
47  0.02499    0.44    0.098        0.17
48  0.03499    0.43    0.087        0.15
49  0.00999    0.42    0.076        0.24

Student DataSet

In [10]:
import pandas as pd
df = pd.read_csv('/content/Student-Dataset.csv')

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Roll_No                10 non-null     int64
 1   Gender                 10 non-null     object
 2   Department             10 non-null     object
 3   CGPA                   10 non-null     float64
 4   Number_of_Backlogs     10 non-null     int64
 5   Attendance_Percentage  10 non-null     int64
 6   Placement_Status       10 non-null     object
 7   Salary                 10 non-null     int64
dtypes: float64(1), int64(4), object(3)
memory usage: 772.0+ bytes

In [11]:
# Label Encoding - Placement Status

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Placement_Status'] = le.fit_transform(df['Placement_Status'])
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,1,450000
1,102,Male,IT,7.5,1,85,0,0
2,103,Female,ENTC,9.1,0,96,1,550000
3,104,Male,Mechanical,6.8,2,78,0,0
4,105,Female,Computer,8.7,0,88,1,480000
5,106,Male,Civil,7.2,3,72,0,0
6,107,Female,IT,8.9,0,91,1,500000
7,108,Male,Computer,6.5,1,80,0,0
8,109,Female,ENTC,7.8,0,84,1,420000
9,110,Male,Mechanical,7.0,2,76,0,0

In [12]:
# One Hot Encoding - Department

df_encoded = pd.get_dummies(df, columns=['Department'])

print(df_encoded)

   Roll_No  Gender  CGPA  Number_of_Backlogs  Attendance_Percentage  \
0      101  Female   8.2                   0                     92
1      102    Male   7.5                   1                     85
2      103  Female   9.1                   0                     96
3      104    Male   6.8                   2                     78
4      105  Female   8.7                   0                     88
5      106    Male   7.2                   3                     72
6      107  Female   8.9                   0                     91
7      108    Male   6.5                   1                     80
8      109  Female   7.8                   0                     84
9      110    Male   7.0                   2                     76

   Placement_Status  Salary  Department_Civil  Department_Computer  \
0                 1  450000             False                 True
1                 0       0             False                False
2                 1  550000             False                False
3                 0       0             False                False
4                 1  480000             False                 True
5                 0       0              True                False
6                 1  500000             False                False
7                 0       0             False                 True
8                 1  420000             False                False
9                 0       0             False                False

   Department_ENTC  Department_IT  Department_Mechanical
0            False          False                  False
1            False           True                  False
2             True          False                  False
3            False          False                   True
4            False          False                  False
5            False          False                  False
6            False           True                  False
7            False          False                  False
8             True          False                  False
9            False          False                   True

In [13]:
# Dummies - Department

df_dummy = pd.get_dummies(df, columns = ['Department'], drop_first = True)
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,1,450000
1,102,Male,IT,7.5,1,85,0,0
2,103,Female,ENTC,9.1,0,96,1,550000
3,104,Male,Mechanical,6.8,2,78,0,0
4,105,Female,Computer,8.7,0,88,1,480000
5,106,Male,Civil,7.2,3,72,0,0
6,107,Female,IT,8.9,0,91,1,500000
7,108,Male,Computer,6.5,1,80,0,0
8,109,Female,ENTC,7.8,0,84,1,420000
9,110,Male,Mechanical,7.0,2,76,0,0